name: Build QMK Firmware

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: 'Branch to build'
        options: [master, ferrisSweep-via]
      keyboard:
        description: 'Keyboard to build'
        default: 'ferris/sweep'
      keymap:
        description: 'Keymap to build'
        default: 'via'


concurrency: ci_build-${{ github.event.inputs.branch || github.ref_name }}

jobs:
  ci_builds:
    name: "CI Build"
    runs-on: ubuntu-latest
    timeout-minutes: 1380

    strategy:
      fail-fast: false
      matrix:
        keyboard: ["${{ github.event.inputs.keyboard }}"]
        keymap: ["${{ github.event.inputs.keymap }}"]

    container: ghcr.io/qmk/qmk_cli

    steps:
    - name: Disable safe.directory check
      run : git config --global --add safe.directory '*'

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        ref: ${{ github.event.inputs.branch || github.ref }}

    - name: Install dependencies
      run: pip3 install -r requirements.txt

    - name: Run `qmk mass-compile` (keymap ${{ matrix.keymap }})
      run: |
        export NCPUS=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null)
        qmk compile -kb ${{ matrix.keyboard }} -km ${{ matrix.keymap }}|| touch .failed

    - name: 'Upload artifacts'
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: artifacts-${{ github.event.inputs.branch || github.ref_name }}-${{ matrix.keymap }}
        if-no-files-found: ignore
        path: |
          *.bin
          *.hex
          *.uf2
          .build/failed.*
